# Generated by Django 3.2.5 on 2021-07-12 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_cliente_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_fiscal', models.CharField(max_length=200)),
                ('fecha_factura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('valor_factura', models.FloatField(default=0.0)),
                ('moneda', models.CharField(max_length=10)),
                ('estado_factura', models.IntegerField(default=1)),
                ('pais_factura', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.cliente')),
            ],
        ),
    ]
