# Generated by Django 3.2.5 on 2021-07-12 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_fiscal', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('contacto', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=200)),
                ('mail_contacto', models.EmailField(max_length=200)),
                ('pais', models.CharField(max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2021, 7, 12, 7, 51, 45, 546626), verbose_name='date published')),
                ('fecha_inactivo', models.DateTimeField(null=True, verbose_name='desactived date')),
            ],
        ),
    ]
